server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DewmalPerera/spring-cloud-config-repo
          search-paths:
            - 'primary-config-store/*service'


