server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DewmalPerera/microservices-config-store
          search-paths:
            - 'service-config/*service'


